# Generated by Django 4.0.5 on 2022-08-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
